// Export helpers: CSV download and a printable status report (Save as PDF via print).
import { phaseLabel, STATUS_LABEL } from "./constants.js";

function download(filename, text, mime) {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

const csvCell = (v) => `"${String(v ?? "").replace(/"/g, '""')}"`;

export function exportCsv(items, projectName) {
  const cols = ["title", "phase", "status", "risk", "owner", "start", "due"];
  const header = cols.join(",");
  const rows = items.map((i) => cols.map((c) => csvCell(i[c])).join(","));
  const safe = (projectName || "project").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  download(`${safe}-items.csv`, [header, ...rows].join("\n"), "text/csv");
}

// Opens a clean, printable status report in a new window. The user can then
// "Save as PDF" from the print dialog — no extra dependency needed.
export function printReport(items, projectName) {
  const today = new Date().toISOString().slice(0, 10);
  const counts = items.reduce((acc, i) => ((acc[i.status] = (acc[i.status] || 0) + 1), acc), {});
  const atRisk = items.filter((i) => i.risk === "high" && i.status !== "done");

  const rows = items
    .map(
      (i) => `<tr>
        <td>${esc(i.title)}</td>
        <td>${esc(phaseLabel(i.phase))}</td>
        <td>${esc(STATUS_LABEL[i.status] || i.status)}</td>
        <td>${esc(i.risk)}</td>
        <td>${esc(i.owner)}</td>
        <td>${esc(i.due)}</td>
      </tr>`
    )
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(projectName)} — status report</title>
    <style>
      body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #1f2733; margin: 40px; }
      h1 { font-size: 20px; margin-bottom: 2px; } .sub { color: #5a6473; font-size: 13px; margin-bottom: 20px; }
      .summary { font-size: 13px; margin-bottom: 16px; } .summary span { margin-right: 16px; }
      table { width: 100%; border-collapse: collapse; font-size: 12px; }
      th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e0e5ee; }
      th { background: #f4f6fb; } .risk { color: #b00; }
      .disclaimer { margin-top: 24px; font-size: 10px; color: #888; }
    </style></head><body>
    <h1>${esc(projectName)}</h1>
    <div class="sub">Project status report · generated ${today}</div>
    <div class="summary">
      <span><b>${items.length}</b> items</span>
      <span>${counts.done || 0} done</span>
      <span>${counts.in_progress || 0} in progress</span>
      <span>${counts.review || 0} in review</span>
      <span>${counts.backlog || 0} backlog</span>
      <span class="risk">${atRisk.length} high-risk open</span>
    </div>
    <table><thead><tr><th>Title</th><th>Phase</th><th>Status</th><th>Risk</th><th>Owner</th><th>Due</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <div class="disclaimer">Generated by ClearPath QMS — educational tool, not regulatory advice.</div>
    </body></html>`;

  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}

function esc(s) {
  return String(s ?? "").replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c]);
}
